CREATE TABLE `hous_control_information` (
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号id',
	`creator` int(11) DEFAULT NULL COMMENT '创建人',
	`create_time` datetime DEFAULT NULL COMMENT '创建时间',
	`modifier` int(11) DEFAULT NULL COMMENT '修改者',
	`modify_time` datetime DEFAULT NULL COMMENT '修改时间',
	`is_delete` tinyint(4) unsigned zerofill DEFAULT NULL COMMENT '0不删除1已删除',
	`process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程ID',
	`project_id` int(11) DEFAULT NULL COMMENT '项目编号',
	`name_identification_consistent` tinyint(4) DEFAULT NULL COMMENT '姓名身份证是否一致',
	`affiliates_number` int(4) DEFAULT NULL COMMENT '关联企业数量',
	`follow_enterprises_category` tinyint(4) DEFAULT NULL COMMENT '关注类企业类别',
	`is_executed` tinyint(4) DEFAULT NULL COMMENT '是否有被执行',
	`items` int(4) DEFAULT NULL COMMENT '笔数',
	`money` decimal(20,2) DEFAULT NULL COMMENT '金额',
	`concluded` varchar(128) DEFAULT NULL COMMENT '结案',
	`occupied_channel` tinyint(4) DEFAULT NULL COMMENT '已被占通道',
	`maximum_mortgage` tinyint(4) DEFAULT NULL COMMENT '已上最高额抵押',
	`judicial_inquiry` tinyint(4) DEFAULT NULL COMMENT '司法查询/行政限制',
	`arrived_nature` tinyint(4) DEFAULT NULL COMMENT '一抵性质',
	`against_bank_name` varchar(64) DEFAULT NULL COMMENT '一抵银行名称',
	`arrived_amount` decimal(20,2) DEFAULT NULL COMMENT '一抵金额',
	`arrived_rates` decimal(20,2) DEFAULT NULL COMMENT '一抵利率',
	`assessed_value` decimal(20,2) DEFAULT NULL COMMENT '评估值(元)',
	`fast_bid` decimal(20,2) DEFAULT NULL COMMENT '快出价(元)',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='风控信息表(面审)';