CREATE TABLE `hous_data_list` (
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号id',
	`creator` int(11) DEFAULT NULL COMMENT '创建人',
	`create_time` datetime DEFAULT NULL COMMENT '创建时间',
	`modifier` int(11) DEFAULT NULL COMMENT '修改者',
	`modify_time` datetime DEFAULT NULL COMMENT '修改时间',
	`is_delete` tinyint(4) unsigned zerofill DEFAULT NULL COMMENT '0不删除1已删除',
	`process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程ID',
	`project_id` int(11) DEFAULT NULL COMMENT '项目编号',
	`account_book` tinyint(4) DEFAULT NULL COMMENT '户口本',
	`marriage_certificate` tinyint(4) DEFAULT NULL COMMENT '结婚证',
	`divorce_certificate` tinyint(4) DEFAULT NULL COMMENT '离婚证',
	`divorce_agreement` tinyint(4) DEFAULT NULL COMMENT '离婚协议',
	`civil_mediation` tinyint(4) DEFAULT NULL COMMENT '民事调解书',
	`court_verdict` tinyint(4) DEFAULT NULL COMMENT '法院判决书',
	`only_housing` tinyint(4) DEFAULT NULL COMMENT '是否唯一住房',
	`deed` tinyint(4) DEFAULT NULL COMMENT '房产证',
	`purchase_contract` tinyint(4) DEFAULT NULL COMMENT '购房合同',
	`lease_contract` tinyint(4) DEFAULT NULL COMMENT '租赁合同',
	`mortgage_loan_contract` tinyint(4) DEFAULT NULL COMMENT '抵押贷款合同',
	`loan_card` tinyint(4) DEFAULT NULL COMMENT '贷款卡',
	`credit_report` tinyint(4) DEFAULT NULL COMMENT '征信报告',
	`two_or_five` tinyint(4) DEFAULT NULL COMMENT '满二或满五',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='资料清单表(权证下户)';