CREATE TABLE `hous_enquiry_institution` (
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号id',
	`creator` int(11) DEFAULT NULL COMMENT '创建人',
	`create_time` datetime DEFAULT NULL COMMENT '创建时间',
	`modifier` int(11) DEFAULT NULL COMMENT '修改者',
	`modify_time` datetime DEFAULT NULL COMMENT '修改时间',
	`is_delete` tinyint(4) unsigned zerofill DEFAULT NULL COMMENT '0不删除1已删除',
	`process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程ID',
	`project_id` int(11) DEFAULT NULL COMMENT '项目编号',
	`institution_name` varchar(128) DEFAULT NULL COMMENT '机构名称',
	`mortgage` tinyint(4) DEFAULT NULL COMMENT '有无抵押',
	`seizure` tinyint(4) DEFAULT NULL COMMENT '有无查封',
	`business_occupancy` tinyint(4) DEFAULT NULL COMMENT '有无业务占用',
	`net_signed_occupancy` tinyint(4) DEFAULT NULL COMMENT '网签占用',
	`hochstbetragshypothek` tinyint(4) DEFAULT NULL COMMENT '是否为最高额抵押',
	`affiliate` tinyint(4) DEFAULT NULL COMMENT '是否有关联企业',
	`legal_process_performed` tinyint(4) DEFAULT NULL COMMENT '是否有进入法律程序的被执行信息',
	`remark` varchar(255) DEFAULT NULL COMMENT '备注',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='查询机构表';