CREATE TABLE `hous_orito_information` (
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号id',
	`creator` int(11) DEFAULT NULL COMMENT '创建人',
	`create_time` datetime DEFAULT NULL COMMENT '创建时间',
	`modifier` int(11) DEFAULT NULL COMMENT '修改者',
	`modify_time` datetime DEFAULT NULL COMMENT '修改时间',
	`is_delete` tinyint(4) unsigned zerofill DEFAULT NULL COMMENT '0不删除1已删除',
	`process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程ID',
	`project_id` int(11) DEFAULT NULL COMMENT '项目编号',
	`property_address_id` varchar(32) DEFAULT NULL COMMENT '房产地址',
	`property_address` varchar(128) DEFAULT NULL COMMENT '房产详细地址',
	`community_name` varchar(128) DEFAULT NULL COMMENT '小区名称',
	`building_brands` tinyint(4) DEFAULT NULL COMMENT '楼牌号是否与房本一致',
	`living_people` tinyint(4) DEFAULT NULL COMMENT '居住人含',
	`furnishing_status` tinyint(4) DEFAULT NULL COMMENT '装修状况',
	`room` int(3) DEFAULT NULL COMMENT '房屋户型(室)',
	`hall` int(3) DEFAULT NULL COMMENT '房屋户型(厅)',
	`guard` int(3) DEFAULT NULL COMMENT '房屋户型(卫)',
	`floor` int(3) DEFAULT NULL COMMENT '所在楼层',
	`total_floors` int(3) DEFAULT NULL COMMENT '总楼层',
	`housing_orientation` tinyint(4) DEFAULT NULL COMMENT '房屋朝向',
	`living_conditions` tinyint(4) DEFAULT NULL COMMENT '居住情况',
	`purchasing_power` tinyint(4) DEFAULT NULL COMMENT '租户签署放弃优先购买权',
	`investigator` varchar(64) DEFAULT NULL COMMENT '调查员',
	`survey_time` datetime DEFAULT NULL COMMENT '调查日期',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='下户信息表(权证下户)';