CREATE TABLE `pl_borrow_requirement` (
	`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '借款需求表-主键',
	`creator` int(11) DEFAULT NULL COMMENT '创建人',
	`create_time` datetime DEFAULT NULL COMMENT '创建时间',
	`modifier` int(11) DEFAULT NULL COMMENT '修改者',
	`modify_time` datetime DEFAULT NULL COMMENT '修改时间',
	`is_delete` tinyint(4) unsigned zerofill DEFAULT NULL COMMENT '0不删除1已删除',
	`process_instance_id` varchar(64) DEFAULT NULL COMMENT '流程ID',
	`project_id` int(11) DEFAULT NULL COMMENT '项目编号',
	`consult_id` int(11) DEFAULT NULL COMMENT '咨询ID',
	`customer_id` int(11) DEFAULT NULL COMMENT '客户ID',
	`account` decimal(20,2) DEFAULT '0.00' COMMENT '借款需求金额',
	`borrowing_time` datetime DEFAULT NULL COMMENT '借款日期',
	`product_id` int(11) DEFAULT NULL COMMENT '产品ID',
	`repayment_type` tinyint(4) DEFAULT NULL COMMENT '还款方式',
	`time_limit` int(11) DEFAULT NULL COMMENT '借款期限按/月',
	`project_belongs` tinyint(4) DEFAULT NULL COMMENT '项目所属',
	`financial_advisers` varchar(64) DEFAULT NULL COMMENT '金融顾问',
	`institution_name` tinyint(4) DEFAULT NULL COMMENT '机构名称',
	`salesman` varchar(64) DEFAULT NULL COMMENT '业务员',
	`borrow_use` varchar(255) DEFAULT NULL COMMENT '借款用途',
	`repayment_source` varchar(255) DEFAULT NULL COMMENT '还款来源',
	`remark` varchar(255) DEFAULT NULL COMMENT '借款说明',
	PRIMARY KEY (`id`),
	KEY `consult_id` (`consult_id`) USING BTREE,
	KEY `project_id` (`project_id`) USING BTREE,
  	KEY `process_instance_id` (`process_instance_id`) USING BTREE,
  	KEY `creatorIndex` (`creator`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='借款需求表';